name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: .\run.ps1
      shell: powershell
    - uses: actions/upload-artifact@v2
      with:
        name: packages
        path: output/packages/